name: Build CI
on: [push]
jobs:
    client:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  token: ${{ secrets.SECRETS_TOKEN }}
                  submodules: true
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install
              run: |
                  yarn
            - name: Setup Expo
              run: |
                  npm install -g expo-cli
                  expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
            - name: Build and publish client
              run: |
                  cd client
                  expo publish -c --release-channel ${GITHUB_REF##*/}
    server:
        runs-on: google/cloud-sdk:alpine
        steps:
            - uses: actions/checkout@v1
              with:
                  token: ${{ secrets.SECRETS_TOKEN }}
                  submodules: true
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install
              run: |
                  yarn
            - name: Setup GCloud
              uses: actions/gcloud/auth@master
              env:
                  GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
            - name: Build server
              run: |
                  cd server
                  yarn prestart
