name: Build CI
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install
              run: |
                  npm install -g expo-cli
                  yarn
                  expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
            - name: Build
              run: |
                  cd client
                  expo build:android
            - name: Download assets
              run: |
                  expo url:apk | xargs wget -o client.apk
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: client.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
