name: Test CI
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: yarn install, and test
              run: |
                  yarn
                  yarn test
              env:
                  CI: true
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1.0.2
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  flags: unittests
